### ISSUE TITLE
Question on 'password' grant vs 'authorization code' grant

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-guides/tut-spring-boot-oauth2#1]
In the tutorial, you write:

> Password grant is appropriate for a native or mobile application, and where you have a local user database to store and validate the credentials. For a web app, or any app with "social" login, like ours, you need the "authorization code" grant, and that means you need a browser to handle redirects and render the user interfaces from the external providers.

I am coding an application that has a server with Spring Boot and has administrative website using AngularJS. There is also a public frontend website that is coded in PHP that uses the REST API of the Spring Boot server. I need to add security to this scenario. They want social logins next to username/password logins for people that do not have facebook or twitter.

The PHP server acts the same as a "mobile client" since the communication to the Spring Boot server is all done through that. So I think I need "password" grant. But then you say for social login, you need "authorization code" grant. I am confused :) Is is possible what we need to do?

**Comment by dsyer** [comment]
Just to repeat the message above for the sake of avoidance of doubt: it's better to forget password grant unless you actually have a native or mobile app; browser based apps are better implemented with other mechanisms.

Remember this: authentication of users by your authorization server during the auth code (and implicit) grant is *completely* orthogonal to the oauth2 process. You can implement it in any way you choose, including a traditional, out-of-the-box Spring Security login form if you choose, or social login as in this guide, or both. There's an example with a login form in Angular in the other tutorial: https://spring.io/guides/tutorials/spring-security-and-angular-js/#_the_login_page_angular_js_and_spring_security_part_ii. You should be able to add that alongside the social examples in this tutorial with very little friction (it's just a `.formLogin()` in the Spring Security configuration).

**Comment by wimdeblauwe** [comment]
I am afraid that just confused me more :)

For testing, I added `.formLogin()`  to the "click" example. I then tried to simulate the PHP server loggin into the application using curl:

    curl -d j_username=user -d j_password=<auto-generated-pwd-here> -L http://localhost:8080/

But that fails with:

    {"timestamp":1453384158286,"status":403,"error":"Forbidden","message":"Expected CSRF token not found. Has your session expired?","path":"/"}

I know I can disable CSRF, but I don't want to disable it as it brings extra security. How would I do the login from curl?

**Comment by dsyer** [comment]
The other tutorial (in the link above) shows you how to make AngularJS talk to Spring Security so that CSRF features on both sides work. It also doesn't use `formLogin()` though, it uses `.httpBasic()`, so you have created some friction there. Since you specifically ask about curl though, you need to get a CSRF token and a cookie from the server (the cookie will be in the response to the initial request that redirects you to the login page, the CSRF token will not unless you add the custom filter from the tutorial).

Aside: note that the default parameter names for form login do not have the "j_" prefix, so that isn't going to work, even if you get the CSRF to behave.

**Comment by wimdeblauwe** [comment]
I have seen that tutorial (I must have read it about a dozen times by now) and I did notice that it uses Basic auth. But this is not secure from what I have heared and read. So I don't think I can see this as a production ready example?

**Comment by dsyer** [comment]
What makes it "not secure"?

**Comment by wimdeblauwe** [comment]
This is what I have understood from this video: http://spring.io/blog/2016/01/12/springone2gx-2015-replay-the-state-of-securing-restful-apis-with-spring

**Comment by dsyer** [comment]
I don't think anything Rob says there makes the sample in the tutorial "not secure". I'll have to watch it to makes sure, but if you have a username and a password and you want to authenticate with a JavaScript client, I don't see much advantage either way.

**Comment by wimdeblauwe** [comment]
See 11:09 to 11:55 for the relevant part of the video.

**Comment by dsyer** [comment]
That was kind of a throwaway comment Rob made. There's a slide at 23:18 or so as well, but he never really talks about HTTP basic in detail. I think he's just using the fact that people have a folklore about HTTP basic and he wants the audience to fall into traps of assumptions he forces them to make. Notice he uses Basic in the sample app later in the presentation as well (the one with Spring Session).

IMO Basic just as secure as a form with username and password for the purposes of authentication and establishing a session. That is to say they are interchangeable from the point of view of security.

**Comment by dsyer** [comment]
N.B. not even native apps should use password grant according to the newest received wisdom (e.g. see this spec: https://tools.ietf.org/html/draft-ietf-oauth-native-apps-00). Nice for demos, but that's about it, in other words.
