### ISSUE TITLE
Is this tutorial suitable to use with mobile authentication?

### ISSUE THREAD

**Issue by nedijahij** [spring-guides/tut-spring-boot-oauth2#112]
I am thinking of creating an app on mobile phone and authenticate using username/password or Github through OAuth2. As in this sample, I see it uses cookie to identify user so i am not sure if it is mobile friendly. Furthermore, if user is authenticated through Github on mobile app, then how can they get access token from my backend server? do i have to hard code call some route manually? Please elaborate. I am really confusing about this. Thank you.

**Comment by dsyer** [comment]
This is a tutorial about Spring (so the backend), and it happens to use a regular browser client as an example frontend. A mobile frontend could be implemented, I am sure. This is indeed not a tutorial about mobile apps (there are other sources for such material, e.g. you could try our friends at Okta). When all is said and done though, HTTP clients all should be able to cope well with cookies, so it would not surprise me to learn that a mobile development environment would contain such an HTTP client. But this is the wrong place to look for examples.

**Comment by nedijahij** [comment]
Hi @dsyer, what i really mean is that, how can I get access token, and refresh token after it's authenticated by github. I could not find detail about how extracting these info. Please let me know how can i do that.

**Comment by dsyer** [comment]
The samples here use the auth code flow (which is recommended even for mobile clients AFAIK). There is no access token on the client side.

> frontend will request to github and get access token and then send it to backend server

That's what the samples here do. It's how OAuth2 works, generally speaking. What you call "frontend" is not what I meant earlier (my "frontend" is the client browser).
