### ISSUE TITLE
How to create my own Authorization Server

### ISSUE THREAD

**Issue by zhousean** [spring-guides/tut-spring-boot-oauth2#119]
Just noticed that the tutorial removed the section for creating its own authorization server. Is there any reason the section is removed? Will it be added back? I am actually looking into an OAuth solution with my own Authorization Server.

**Comment by dsyer** [comment]
The authorization server features were not ported over form the old spring-security-oauth2 project to spring-security. I believe that they might eventually be ported, but I'm not holding my breath. This one looks promising: https://github.com/ory/hydra. It has a well-defined contract for login and "consent" as a standalone service, which could quite easily be written in Spring.
