### ISSUE TITLE
[auth-server] "/me" can not access after authenticated.

### ISSUE THREAD

**Issue by zhangyanwei** [spring-guides/tut-spring-boot-oauth2#13]
always get the following error :(
```xml
<oauth>
    <error_description>
        Full authentication is required to access this resource
    </error_description>
    <error>unauthorized</error>
</oauth>
```

**Comment by dsyer** [comment]
Stupid question: did you authenticate the request? Look at the headers and you will see what the problem is.

**Comment by zhangyanwei** [comment]
authenticated, "/user" works well, but "/me" not work.

**Comment by dsyer** [comment]
It works for me. You haven't really described what you are doing to get the above error. I expect you didn't authenticate the request.

**Comment by zhangyanwei** [comment]
the following are steps I have tested.
1. access "/me" endpoint, will get "unauthorized" error.
2. access "/user" endpoint, will redirect to "/" according the web security configuration.
3. access "/login/github" endpoint, and entered the username and password, then authenticate it, will redirect to "/".
4. access "/user" endpoint, will get the information of authenticated user.
5. access "/me" endpoint, still get the same error "unauthorized".

I am using spring boot 1.3.3.RELEASE, and spring security oauth2 2.0.9.RELEASE.

**Comment by dsyer** [comment]
"access" is not very precise. If you are doing this all in a browser, then naturally, you will not be sending the correct authentication. Is that what you did?
