### ISSUE TITLE
facebook authorization issue

### ISSUE THREAD

**Issue by mantuu** [spring-guides/tut-spring-boot-oauth2#15]
The very simple example does not work, since facebook showing an error message after I log in in facebook authorization form. Anyone any ideas? Is the api broken?

**Comment by dsyer** [comment]
Works for me last time I tried it. Can you be more specific about the error? Maybe facebook has disabled the client (you can register for your own id and secret).

**Comment by mantuu** [comment]
The error message says that basically the app is not set up: "This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions" 

dsyer I appreciate your help. thank you for your quick answer

**Comment by dsyer** [comment]
Maybe it only works for me then because I registered the app. Can you register your own and use its credentials instead of the defaults?

**Comment by dsyer** [comment]
Actually try again now with the default credentials. I just tweaked the settings on facebook and it says "Your app is currently live and available to the public."

**Comment by mantuu** [comment]
works!!!
