### ISSUE TITLE
Fail to obtain oauth token

### ISSUE THREAD

**Issue by LeeU1911** [spring-guides/tut-spring-boot-oauth2#23]
Hi all,

I cloned the repo and checkout the first commit which is the simple app with oauth login against Facebook. But I faced an error which says "Could not obtain access token" after logging in and approve the permission successfully in Facebook page.

Does anyone experience the same issue?

Thank you all.

Note:
* I'm running on Windows.
* I increased the version number of spring-boot-starter-parent to 1.3.5.RELEASE since I ran into build error with original version in pom.xml file.
* I tried to build another demo project from scratch following the tutorial but also failed with the same error.

**Comment by dsyer** [comment]
> the first commit

That's history. I would start with master if I were you. There's a sequence of apps with features that build up to something that works.

**Comment by LeeU1911** [comment]
Hi Dave,

After receiving your reply, I re-do it again. Here's what I did:
1. Clone the repo: https://github.com/spring-guides/tut-spring-boot-oauth2 into folder tut-spring-boot-oauth2
2. cd into tut-spring-boot-oauth2/simple folder
3. Issue command: mvn clean install followed by mvn spring-boot:run
4. Open an incognito chrome browser and load http://localhost:8080
5. Log into Facebook with my credentials, accept the permission
6. Browser displays "Whitelabel error page" saying "Could not obtain access token"

Please help to see if I missed anything. I'm still running on Windows.

Thanks a lot!

**Comment by dsyer** [comment]
Works for me. Facebook might be limiting access to this app (which is registered in my name). Maybe you could register your own and configure it to make sure?

**Comment by firefoxNX** [comment]
I am facing the same issue as @LeeU1911. When tracing using Charles HTTP Proxy I don't see call to provider's oauth2/token endpoint. I have tried with Facebook, Github, Dropbox.

**Comment by dsyer** [comment]
What do you mean by "redirect_uri in Facebook app"? If you registered your own app you can tell them `http://localhost:8080`.

**Comment by firefoxNX** [comment]
Thanks using redirect_uri = http://localhost:8080 works.
