### ISSUE TITLE
Logout not success, login automatic (don't ask permission or username/password)

### ISSUE THREAD

**Issue by donhuvy** [spring-guides/tut-spring-boot-oauth2#25]
Step 1. Login by GitHub account.
Step 2. Accept perrmission.
Step 3. Log out
Step 4. Press link **login by GitHub account again**, automatic sent me to registered user area, **didn't ask me permission or username/password**.

**Comment by dsyer** [comment]
That's expected: you wouldn't want this app to log you out of github would you?

**Comment by donhuvy** [comment]
Because after I log out (log out of site http://localhost:8080/tut-spring-boot-oauth2), web application must remove my identification information from browser. 

Then, when I press login again. In the reality, I don't need login action, because web application automatic redirect me to protected area without asking for permission.

Please explain for me!

**Comment by dsyer** [comment]
You already gave permission for the grant. Most providers don't make you do it again (at least without a timeout or something), so the app can collect all the data it needs to authenticate you without needing to prompt for more. It's just the way it works.

**Comment by donhuvy** [comment]
Thank you!

I make an experiment. I try login to GitLab by my GitHub account (https://gitlab.com/users/sign_in), then logout, then login (automatic login).
