### ISSUE TITLE
Android integration for github example

### ISSUE THREAD

**Issue by thiagotigaz** [spring-guides/tut-spring-boot-oauth2#26]
Hi,

I'm using the github example to start a new app but i'm not sure how to handle it on android client.
My plan is to have a web(angularJs), android and ios using only facebook as authentication.

How the communication between Android and api should be done after user signs in with facebook sdk(Login button) on android?

I want to offload everything to facebook and don't have my own oauth server for now, but i'm not sure how to do it. 

What should I include to the request to the api?

**Comment by dsyer** [comment]
People tell me that the HTTP client stack on all platforms is very "browser like" and it's easy to use cookies. So if I were you I'd stick to plain cookie authentication with your app (it's what you get out of the box anyway with the samples here), and a web view for the authentication. One of these days I'll get round to actually trying it, but for now I'm just repeating what I'm told.

**Comment by thiagotigaz** [comment]
OK, i'm trying to follow this approach

The problem is that after i use facebook android sdk to authenticate with their oauth server i just receive the token.

How should i do the request to my api passing the token so that i authenticate with spring security and receive the cookie back.

i mean something like this

http://localhost:8080/login/facebook?token=tokenigotusingfacebooksdktologin

Because what i see is that it does a request like this
http://localhost:8080/login/facebook?code=codeusedbyspringtogetaccesstoken

So actually the server uses app id and app secret as the client for facebook oauth server and the code to get the access token on behalf of the user. It seens using facebook sdk on android i'm one step ahead(already with token) and what i want is to use the token to authenticate with my api. Is it the correct approach or i'm missing something?

**Comment by dsyer** [comment]
It's not so much one step ahead as on a completely different path. If you want to write an authentication filter that uses a token that you obtain and send from your client, there's nothing stopping you, but the samples in this tutorial don't work that way.
