### ISSUE TITLE
Typo in OAuth 2 Developers Guide

### ISSUE THREAD

**Issue by nurgasemetey** [spring-guides/tut-spring-boot-oauth2#28]
Hello guys,

I want to point to small typo in this guide: http://projects.spring.io/spring-security-oauth/docs/oauth2.html.

It is under chapter **Configuring the Endpoint URLs** where is ***note***:

> 
Note: if your Authorization Server ... **Fo** those ...

With regards

**Comment by dsyer** [comment]
Thanks for the report. For future reference, please note that Spring Security OAuth2 is in its own github repository (https://github.com/spring-projects/spring-security-oauth) and the user guide is in the source code there, not here.
