### ISSUE TITLE
Oauth2 + angular js

### ISSUE THREAD

**Issue by atiwari54** [spring-guides/tut-spring-boot-oauth2#33]
Have 1 bundle for Auth server(with mongo DB) which is running on separate port and one more bundle for UI and login and home page is in UI bundle. now how can i validate authorisation for login page.(user must be redirect to login if he hits direct home page url and not login )

**Comment by dsyer** [comment]
That doesn't seem like a well formed question to me. Did you know there is a tutorial on using Spring Security with Aggular JS here: https://spring.io/guides/tutorials/spring-security-and-angular-js/
