### ISSUE TITLE
Using facebook api

### ISSUE THREAD

**Issue by mzeitlin** [spring-guides/tut-spring-boot-oauth2#34]
With the example given,  should I be able to use the Spring Social Facebook apis to retrieve social info based on that token?  For example:

`	@RequestMapping({ "/user" })
	public Map<String, String> user(Principal principal) {
		Map<String, String> map = new LinkedHashMap<>();
		if(facebook.isAuthorized())
			map.put("name", facebook.userOperations().getUserProfile().getFirstName() + facebook.userOperations().getUserProfile().getLastName());
		return map;
	}`

**Comment by dsyer** [comment]
The sample apps here s not use spring social, so that code would take some effort to configure it to work literally. You can still use the `OAuth2RestTemplate` to interact with Facebook graph API though.

**Comment by mzeitlin** [comment]
Is there an easy way to get the bearer token from the Principal?  I figured I could just pass that to the FacebookTemplate constructor and it should work......

**Comment by dsyer** [comment]
Look at the `Principal` and see if you can downcast it to `Authentication`. If you can then the access token is in the "details" property. A better place to get it is the `OAuth2ClientContext` (you can get the refresh token too that way).

**Comment by mzeitlin** [comment]
Yep!  it worked,  it was not pretty,  but this is a first step for anyone else interested in this:

`		Facebook facebook = new FacebookTemplate(((OAuth2AuthenticationDetails)((OAuth2Authentication)p).getDetails()).getTokenValue());`

I will look at using the OAuth2ClientContext next.  I appreciate all the help,  especially understanding that this wasn't really an issue with the tutorial.
