### ISSUE TITLE
How to run Client Client Application?

### ISSUE THREAD

**Issue by PrithiviRajG** [spring-guides/tut-spring-boot-oauth2#38]
When I run Client Application separately, I am getting 404 error which accessing http://192.168.1.4:9999/ URL from local.

**Comment by dsyer** [comment]
Are you running the auth server as well on port 9999? Is 192.168.1.4 your local IP address? Why is it not using localhost? Some more detail on what you did and what you saw would help to identify whether you made a mistake and what that might be.

**Comment by PrithiviRajG** [comment]
I am running both Social Application (port 8080) and client application (port 9999) simultaneously with two STS.

Social Application is up and working fine but when I run Client I am getting 404.

In read me, its mentioned to use IP address to access client application, but I used both localhost and local IP address to access and they are not working.

Thanks

**Comment by dsyer** [comment]
The client in the sample code runs at http://localhost:9999/client. Try that.

I removed the section on using a local IP address in 797e492. It was confusing.

**Comment by pcompassion** [comment]
so how to run the client application? :(

**Comment by dsyer** [comment]
> so how to run the client application?

In your IDE right click on the main method and select "Run".

**Comment by pcompassion** [comment]
Thanks for the quick response.

I ran server with `mvn spring-boot:run`

I think select Run only runs server as well?

**Comment by dsyer** [comment]
It works for me. Please consult the documentation for your IDE to find out how to run a main method in a class.
