### ISSUE TITLE
How to redirect to client application after successful login without @EnableOAuth2Sso annotation

### ISSUE THREAD

**Issue by PrithiviRajG** [spring-guides/tut-spring-boot-oauth2#39]
I am trying to use Angular 2 Front End application as a client which will consume the resource from Spring RESTful Web Service.

So thought of protecting this web service with OAuth 2 authentication and Social Login.

After successful login with Social Login it's not redirecting to the URL (port at which Angular 2 is running http://localhost:3000/) from which I made the request but its redirecting to http://localhost:8080/

http://localhost:3000/ - Front End
http://localhost:8080/ - OAuth

Thanks in advance

**Comment by dsyer** [comment]
I think you can just set the login success URL using the `HttpSecurity` configurer. That's not the same architecture as the samples in this guide, though, so maybe you would get better responses on StackOverflow?
