### ISSUE TITLE
Any guidance on creating an authentication provider?

### ISSUE THREAD

**Issue by eoliphan** [spring-guides/tut-spring-boot-oauth2#40]
I'm interested in creating an 'internal' implementation that uses the OAuth2SSO stuff that's worked through here, but rather than Facebook, etc, I'd like to have an authentication provider that's pointing to my LDAP, database, etc

**Comment by dsyer** [comment]
It's easy to create an authorization server (http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-security-oauth2-authorization-server, https://spring.io/guides/tutorials/spring-security-and-angular-js/#_sso_with_oauth2_angular_js_and_spring_security_part_v, https://github.com/spring-projects/spring-security-oauth/tree/master/samples/oauth2/sparklr, etc.). Why don't you give it a go and come back on StackOverflow with usage questions?

**Comment by eoliphan** [comment]
Cool thanks will give it a whirl, yeah for got i should have done on SO :)
