### ISSUE TITLE
The simple project doesn't work with my FB app - any additional config to do?

### ISSUE THREAD

**Issue by ncastrocosta** [spring-guides/tut-spring-boot-oauth2#43]
Hi everyone!

The 'Simple' project works fine as it is. However, when I changed the FB app to use one of my own, I received the following message:

> URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

It is strange because the only differences are the properties **clientId** and **clientSecret**. Should I have some special configuration on my FB app?

Thanks!

**Comment by dsyer** [comment]
Yes. The app (home page) URI has to match the one your registered with FB. There's nothing you can do in Spring - it's in your FB account.
