### ISSUE TITLE
In tutorial article, token services don't use the oAuth2RestTemplate

### ISSUE THREAD

**Issue by LeaderOne** [spring-guides/tut-spring-boot-oauth2#44]
In the guide, when a user is configuring the token services starting with "Manual Configuration of OAuth2 Client", the token services get set like this:

```
private Filter ssoFilter() {
  OAuth2ClientAuthenticationProcessingFilter facebookFilter = new OAuth2ClientAuthenticationProcessingFilter("/login/facebook");
  OAuth2RestTemplate facebookTemplate = new OAuth2RestTemplate(facebook(), oauth2ClientContext);
  facebookFilter.setRestTemplate(facebookTemplate);
  facebookFilter.setTokenServices(new UserInfoTokenServices(facebookResource().getUserInfoUri(), facebook().getClientId()));
  return facebookFilter;
}
```

This method of setting the token services doesn't use the `OAuth2RestTemplate` that you just created.  Although Facebook and GitHub may not require it, it might be a good idea to put a blurb in there about what that means, or change the guide to set the `RestTemplate` explicitly.  The code  checked out from GitHub does use the template in some examples, which is different than the guide.

**Comment by dsyer** [comment]
I'm not really sure what you mean. It's not true at all that the `OAuth2RestTemplate` in the snippet above doesn't get used (otherwise why would we bother creating it?). Where exactly did you find a difference between the text and the code?

Obviously something is confusing, so we could maybe improve the text in the tutorial, but only if we can agree on what the issue is.

**Comment by LeaderOne** [comment]
You're right, perhaps this is better explained with code.  Right now, the code in the article looks like this:

```
private Filter ssoFilter() {
  OAuth2ClientAuthenticationProcessingFilter facebookFilter = new OAuth2ClientAuthenticationProcessingFilter("/login/facebook");
  OAuth2RestTemplate facebookTemplate = new OAuth2RestTemplate(facebook(), oauth2ClientContext);
  facebookFilter.setRestTemplate(facebookTemplate);
  facebookFilter.setTokenServices(new UserInfoTokenServices(facebookResource().getUserInfoUri(), facebook().getClientId()));
  return facebookFilter;
}
```

My assertion is that it should look like this, even if it isn't explicitly needed:

```
private Filter ssoFilter() {
  OAuth2ClientAuthenticationProcessingFilter facebookFilter = new OAuth2ClientAuthenticationProcessingFilter("/login/facebook");
  OAuth2RestTemplate facebookTemplate = new OAuth2RestTemplate(facebook(), oauth2ClientContext);
  facebookFilter.setRestTemplate(facebookTemplate);

  UserTokenServices facebookTokenServices = new UserInfoTokenServices(facebookResource().getUserInfoUri(), facebook().getClientId()); //Separate out creation of the token services...
  facebookTokenServices.setRestTemplate(facebookTemplate); //Set the rest template for the token services, even if it isn't explicitly needed

  facebookFilter.setTokenServices(facebookTokenServices);
  return facebookFilter;
}
```
Does this make sense?

**Comment by dsyer** [comment]
I guess. But does it somehow stop working if you don't do that? I think the rest template in a `UserInfoTokenServices` is optional, and the app seems to work in this case without it.

**Comment by LeaderOne** [comment]
Yes, you are right, it does work.  But some OAuth services need it.  I figured that out the hard way.

**Comment by dsyer** [comment]
OK, I see. And I can see that the code is different than the text now as well.

**Comment by hynese** [comment]
Note that `UserTokenServices` isn't available anymore. I'm using Spring Boot 2.0.0.M4
