### ISSUE TITLE
Own oauth server with facebook login not using cookie

### ISSUE THREAD

**Issue by sanjaypatel2525** [spring-guides/tut-spring-boot-oauth2#46]
I am using password grant type, and getting access and refresh token form my own oauth server. This access token I am passing in authorization header for each request. 
Now  I am adding facebook login support, but it doesnt seems to return access token to browser, while it is setting up cookie. 
My question is shall I tweek facebook login flow to generate access token from my oauth servers ? or is there any other way to remove cookie support ?

**Comment by dsyer** [comment]
I'm not sure what you mean about "cookie support", or what role you want facebook to play in the flow (there's no way to get a password grant from facebook). Maybe you need to reconsider the use of password grant?

**Comment by sanjaypatel2525** [comment]
I am having rest based microservices. One Auth server other four project are resource server and clients as well. Right now the end user calls /oauth/token passing username and password to get access token. This access token is used authorize all ongoing request. 
But FB login, spring is setting JSESSION_ID in cookie to track the session. I dont have enough knowlege how FB login working for spring but it seems to be using JSESSION_ID from cookie to identify user and this doesn't leaves service restfull.
My idea is to do a workaround, once FB login is successfull, get the user detail and save it in my oauth server, and provide end user an access token for next requests.  Is it good idea or current Spring Oauth2 FB login supports something for rest based services and login. 

 Utmost thanks for replying :)

**Comment by dsyer** [comment]
If your client is a browser (even if it's not probably) I'd say you ought to give up on password grant. Use the cookie for authentication to a gateway layer, and relay the token on to the backend services from there. That's the pattern used in this tutorial (Facebook or other authentication mechanisms are orthogonal).

**Comment by sanjaypatel2525** [comment]
It makes sense. Thanks ..
