### ISSUE TITLE
Logout doesnt seems to be work

### ISSUE THREAD

**Issue by atif92** [spring-guides/tut-spring-boot-oauth2#53]
First of all Thanks for this great work. I am trying to get logged out using a client Application in social-auth-server but Its not logging out, I have registered 3 clients with it, I wish to logout one of them and rest gets logged out automatically i.e Single Log Out

**Comment by dsyer** [comment]
Not really an issue per se, more of a design decision. See also https://github.com/spring-guides/tut-spring-security-and-angular-js/issues/121.

**Comment by atif92** [comment]
Thanks I figured that out and some how implemented in my project.
