### ISSUE TITLE
principal.getName() returns a unique ID instead of name

### ISSUE THREAD

**Issue by atif92** [spring-guides/tut-spring-boot-oauth2#57]
I implemented this program and created an extra social login using facebook and google instead of github.
Now in my client application this controller returns different output for google and different for gmail:
  

```
@RequestMapping("/")
  public String home(Principal user) {
    return "Hello " + user.getName();
  }
```

For gmail I get user's name and for facebook we get some unique ID. why is it different behaviour for different logins, How can we get name in case of facebook?

I also tried changing this to `userInfoUri: https://graph.facebook.com/me?fields=name` 

Now, In my angular `self.user = data.userAuthentication.details.name;` data has the name but this line itself returns a numeric id. 
I also tried doing this:

```
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		String currentPrincipalName = authentication.getName();
		String auth =  (String) authentication.getPrincipal();
```
But both of the last lines still return numeric id for facebook instead of name. can you please help?

**Comment by dsyer** [comment]
The "name" of a `Principal` is usually something unique (it can be a user name, but for Facebook the unique identifier is not human readable, that's just the way it is). You can provide a `PrincipalExtractor` (as a `@Bean` in a Spring Boot application) if you want to do something different, but you only get the data that Facebook send you, so if that doesn't have the value you need you are stuffed.

**Comment by atif92** [comment]
Is it possible for you to write a short principal extractor implementation for this case?

**Comment by atif92** [comment]
I figured it out and can get name on facebook and google both uniformly like this:

```
	@RequestMapping(value = { "/user", "/me"}, method = RequestMethod.GET)
    public Map<String, String> user(Principal principal) {
        Map<String, Object> details = (Map<String, Object>) ((OAuth2Authentication) principal).getUserAuthentication().getDetails();
        Map<String, String> map = new LinkedHashMap<>();
        map.put("name", (String) details.get("name"));
        map.put("email", (String) details.get("email"));
        return map;
    }
```

**Comment by atif92** [comment]
May be it can help anyone similar issue

**Comment by Stanev404** [comment]
@atif92 Do you have any idea why i get only the name but not the email. I'm using your solution.

**Comment by kewp** [comment]
I keep getting a cast error when using you're method above, @atif92 . Could you perhaps post a code example?

**Comment by kewp** [comment]
```bash
class org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken cannot be cast to class org.springframework.security.oauth2.provider.OAuth2Authentication 
```

**Comment by nigaur** [comment]
> May be it can help anyone similar issue

Exactly, it helped me getting displayName instead of Id from Azure Active Directory
