### ISSUE TITLE
Spring Boot 2

### ISSUE THREAD

**Issue by 7fantasy7** [spring-guides/tut-spring-boot-oauth2#62]
Thanks for nice examples, could you please make another one for spring boot 2.x.x?
Or simply describe, what should I change (for example in "github" project)?

**Comment by gregturn** [comment]
We don't plan on upgrade guides or tutorials until Boot's 2.0 release is GA.

**Comment by dsyer** [comment]
We can leave it open till then. This guide will not be trivial to upgrade. I’m not even sure we should attempt it across the board.

**Comment by er-han** [comment]
Any update on the issue, since Boot's 2.0 is released now?

**Comment by kibbled** [comment]
Same, it would be nice to have a full guide of OAuth2 working with Spring Boot 2.0.

**Comment by ggeorgovassilis** [comment]
Most samples work by pinning spring boot version to 2.0.1.RELEASE and webjars-locator to 0.33.
social-manual/application.yml: rename facebook:client tree to security:oauth2:client
However I couldn't get social-auth-server to run; it's looking for GlobalAuthenticationConfigurerAdapter in the wrong package; looks like a dependency missmatch.

**Comment by idcmp** [comment]
In the interim it may be worthwhile to put a disclaimer at the top of the guide that it will not work with Spring Boot 2?

**Comment by dsyer** [comment]
Fixed in 53acfe7
