### ISSUE TITLE
How to Add a Local User Database

### ISSUE THREAD

**Issue by houssemzaier** [spring-guides/tut-spring-boot-oauth2#8]
Hi Spring Developer and Spring Lovers,
First of all I want to thank you for this great free tutorial to start learning about the newest modern tools that Spring Framework give us for free. 
Next I have read this paragraph:

--------------------------------------------------
## How to Add a Local User Database:

Many applications need to hold data about their users locally, even if authentication is delegated to an external provider. We don’t show the code here, but it is easy to do in two steps.

Choose a backend for your database, and set up some repositories (e.g. using Spring Data) for a custom User object that suits your needs and can be populated, fully or partially, from the external authentication.

Provision a User object for each unique user that logs in by inspecting the repository in your /user endpoint. If there is already a user with the identity of the current Principal, it can be updated, otherwise created.

Hint: add a field in the User object to link to a unique identifier in the external provider (not the user’s name, but something that is unique to the account in the external provider)

--------------------------------------------------

This was a quite simple and I have understand it but because I am new to the spring framework I can not get more than the user's name from the principal paramater passed into this method:
  @RequestMapping({ "/user", "/me" })
    public Principal user(Principal principal){
While I can get all the desired info in the frontEnd as a JSON format.

_**So finally my question is how can I get some details about the User Authentication like url to his account with the spring/java apis**_.

I had an idea in my mind and I know that it is not the best solution to do the job but it works: 
it is based on creating a Bean for UserInfo witch has all the info required to parse from the path "/user" then I use the RestTemplate to call this resource and then it parse the needed data. 
It is that it is not the best way to do that so please;
THANKS IN ADVANCE

**Comment by dsyer** [comment]
Downcast the `Principal` to an `Authentication` (or possibly `OAuth2Authentication` and grab the `userAuthentication` from that) and then look in the `details` property. If your user was authenticated using a `UserInfoTokenServices` you will see the `Map` returned from the external provider's user info endpoint.

**Comment by houssemzaier** [comment]
Thank you very much it works with the OAuth2Authentication . 
I was trying for hours with the Authentication object but I've gotten an exception because It can not be downcasted. Thanks a lot
