### ISSUE TITLE
Issue for using Redis

### ISSUE THREAD

**Issue by majinsheng** [spring-guides/tut-spring-boot-oauth2#82]
I am planning to use Redis as a token store. After import spring-boot-starter-data-redis, then wrote blow code:

    @Bean
    public TokenStore tokenStore() {
        return new RedisTokenStore(redisConnection);
    }

But i got an error. 

2018-05-30 17:03:07.864 ERROR 12735 --- [nio-8080-exec-2] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: NestedServletException, Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V

the spring boot version is 

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
        <relativePath /> 
    </parent>

**Comment by dsyer** [comment]
I guess that isn't supported then - the `RedisTokenStore` was written and compiled against an older version of Spring Redis. You could try downgrading that, I suppose (using `spring-data-releasetrain.version`), but there's no guarantee it wouldn't break something else.
