### ISSUE TITLE
Issue in running Simple module with the given pom details and with 2.0.1.RELEASE as parent

### ISSUE THREAD

**Issue by basurohit77** [spring-guides/tut-spring-boot-oauth2#93]
I run the code for the simple module as is, getting error:

     org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates 
     for configuration class [com.example.app.SocialApplication]; nested exception is 
    java.lang.IllegalArgumentException: Unresolvable class definition for class   
    [org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2SsoDefaultConfiguration 
    $NeedsWebSecurityCondition] at org.springframework.context.annotation . 
    ConfigurationClassParser.processImports( ConfigurationClassParser.java:645) ~[spring-context- 
    5.0.5.RELEASE.jar:5.0.5.RELEASE] at org.springframework.context.annotation.Configuration 
    ClassParser.doProcessConfiguration Class(ConfigurationClassParser.java:300) ~[spring-context- 
    5.0.5.RELEASE.jar:5.0.5.RELEASE] at  org.springframework.context.annotation.Configuration 
    ClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context- 
    5.0.5.RELEASE.jar:5.0.5.RELEASE] at  org.springframework.context.annotation.Configuration 
    ClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context 
    -5.0.5.RELEASE.jar:5.0.5.RELEASE] at org.springframework.context.annotation.ConfigurationClass 
    Parser.parse (ConfigurationClassParser.java:170)  ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE] at 
     org.springframework.context.annotation.ConfigurationClassPostProcessor.process 
     ConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316) ~[spring-context- 
     5.0.5.RELEASE.jar:5.0.5.RELEASE] at org.springframework.context.annotation.ConfigurationClass Post 
     Processor. postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring- 
     context-5.0.5.RELEASE.jar:5.0.5.RELEASE] at org.springframework.context.support.PostProcessor 
     Registration Delegate.invokeBean DefinitionRegistryPostProcessors 
     (PostProcessorRegistrationDelegate.java:273)  ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
     at  org.springframework.context.support.PostProcessorRegistration 
     Delegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[spring- 
     context-5.0.5.RELEASE.jar:5.0.5.RELEASE] at  org.springframework.context.support. 
     AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694) ~ 
     [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE] at org.springframework.context.support. 
    AbstractApplication Context.refresh(AbstractApplicationContext.java:532) ~[spring-context- 
    5.0.5.RELEASE.jar:5.0.5.RELEASE] at org.springframework.boot.web.servlet.context. 
    ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring- 
    boot-2.0.1.RELEASE.jar:2.0.1.RELEASE] at org.springframework.boot.SpringApplication.refresh 
    (SpringApplication.java:759)   [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]at 
    org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
    [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE] at org.springframework.boot.SpringApplication.run 
    (SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE] at 
    org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot- 
    2.0.1.RELEASE.jar:2.0.1.RELEASE] at org.springframework.boot.SpringApplication.run
    (SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE] at 
    com.example.app.SocialApplication.main(SocialApplication.java:13) [classes/:na]
    Caused by: java.lang.IllegalArgumentException: Unresolvable class definition for class 
    [org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2Sso 
    DefaultConfiguration$NeedsWebSecurityCondition] at  
    org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:314) ~[spring-core- 
    5.0.5.RELEASE.jar:5.0.5.RELEASE]

please help.

**Comment by basurohit77** [comment]
org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2SsoDefaultConfiguration jar is not available in maven repository. Under org/springframework/boot  there is nothing like autoconfigure folder.
Where to get this jar

**Comment by basurohit77** [comment]
i used:

                 <dependency>
			<groupId>org.springframework.security.oauth.boot</groupId>
			<artifactId>spring-security-oauth2-autoconfigure</artifactId>
			<version>2.0.1.RELEASE</version>
		 </dependency>

both 2.0.0 and 2.0.1. But still getting "Unresolvable class definition for class [org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2SsoDefaultConfiguration$NeedsWebSecurityCondition]"

**Comment by basurohit77** [comment]
[simplefacebookauth.zip](https://github.com/spring-guides/tut-spring-boot-oauth2/files/2648713/simplefacebookauth.zip)

**Comment by basurohit77** [comment]
> It's in the [shim project](https://github.com/spring-projects/spring-security-oauth2-boot/blob/master/spring-security-oauth2-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2SsoDefaultConfiguration.java) (as mentioned in the guide, and included in the dependencies of the samples). That's the one that you seem to have a bum jar for.

Even i copy the package, there are two imports which are not found:

       import org.springframework.boot.autoconfigure.condition.ConditionOutcome;
       import org.springframework.boot.autoconfigure.security.oauth2.client 
      .OAuth2SsoDefaultConfiguration.NeedsWebSecurityCondition;

**Comment by dsyer** [comment]
`ConditionOutcome` is public in `spring-boot-autoconfigure`. You shouldn't need the `Condition` itself to be visible. Like I said, it works for me. You most probably have a bad jar.

**Comment by dsyer** [comment]
There are Facebook and Github examples in this guide. You can’t have autoconfiguration for both at once - that’s why the guide makes manual configs.
