### ISSUE TITLE
Spring OAuth Sample isn't using a secure connection to transfer information

### ISSUE THREAD

**Issue by ocarlsen** [spring-guides/tut-spring-boot-oauth2#94]
Facebook is blocking this tutorial because the connection is not secure.  

At the [Single Sign On With Facebook](https://spring.io/guides/tutorials/spring-boot-oauth2/#_social_login_simple) step, when user goes to http://localhost:8080/, Facebook answers with an ugly popup that says:

```
Facebook has detected Dave Syer Spring OAuth Sample isn't using a secure connection to transfer information.
Until Dave Syer Spring OAuth Sample updates its security settings, you won't be able to use Facebook to log into it.
```
Steps to reproduce:

1. `git clone https://github.com/spring-guides/tut-spring-boot-oauth2.git`
2. `mvn spring:boot run`
3. Navigate to http://localhost:8080/
4. When prompted, log into FB 

You will see this dialog:

<img width="520" alt="screen shot 2018-12-05 at 6 07 18 pm" src="https://user-images.githubusercontent.com/2373329/49556594-66ac3480-f8b9-11e8-946f-74f061c92700.png">

**Comment by dsyer** [comment]
Facebook doesn't block it for me, it just provides you with an option to discontinue. I'm not sure why you would be seeing something different. Maybe you could create an app for yourself at https://developers.facebook.com/ and configure it instead of the default sample credentials.

**Comment by janvryck** [comment]
I encountered the same issue as ocarlsen, which was resolved by creating my own app. Reading Facebooks documentation, localhost should work without SSL as long as the app is still in status 'In Development'.

**Comment by ocarlsen** [comment]
Thanks guys.  Now there is a new wrinkle.  I rebooted my machine and started up the demo, and now when I get directed to Facebook I see this dialog with the option to "Continue Logging in".  However, when I click to continue it seems go go into an infinite loop and keeps showing the same dialog without redirecting back to localhost.

<img width="524" alt="screen shot 2018-12-06 at 9 22 53 am" src="https://user-images.githubusercontent.com/2373329/49607654-7d9b6700-f94b-11e8-84bb-c9c98b3491c8.png">

I will try creating my own app.

**Comment by ocarlsen** [comment]
PS.  It works as expected on Firefox.  I looked into the Chrome console and found this warning, it may be related.

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.facebook.com/dialog/oauth?client_id=233668646673605&redirect_uri=http://localhost:8080/login&response_type=code&state=waLy3P with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by aculver28** [comment]
Just tried this again. Doesn't work on Chrome, Firefox, or Safari. Worked fine when I created my own app though.

**Comment by adrianbob** [comment]
I'm still struggling with this issue. I created my own app and still I cannot get it to work. Facebook doesn't let me set the redirect url to use http even though the status of the app is in development.

![screenshot 2019-01-09 at 18 54 10](https://user-images.githubusercontent.com/24224359/50914816-1a1bc200-1440-11e9-8977-a0e90b8ac176.png)

**Comment by vinayakshedgeri** [comment]
update ur client id at yml or properties file , if you are using spring boot and also create at app in facebook developer page

**Comment by tharikadahanayaka** [comment]
I also fixed it the same way mentioned by @adrianbob .

**Comment by gitkgothatso** [comment]
Even mine was fixed after creating my own app, with basic configs

**Comment by rsbem777** [comment]
I am really new to this.  Could someone give a some additional details on creating my own app with basic configs?  I haven't seen the page referenced above by adrianbob.  Are you adding a Facebook Login and then selecting the www platform?

**Comment by dsyer** [comment]
Yes, that should work. Then look at the lefthand menu and click on Facebook Login-> Settings. They change the UI all the time so it can be a bit hard to keep up.

**Comment by rsbem777** [comment]
I found the pages I was missing.  After setting up the default app do you have to make any changes to the tutorial code?  I saw where there were instructions to add a script to the body tag of all .html files.  So I added the script to index.html file of the simple example.  I am not seeing the glue that holds this all together.  Thanks

**Comment by dsyer** [comment]
No code changes should be necessary. Facebook has some client side code they want you to use, but that's more about Facebook than OAuth2. You just need to change the config file for the client id and secret.

**Comment by rsbem777** [comment]
That worked!  Thanks Dyser.  For anyone else looking for more explicit instructions I edited the tut-spring-boot-oauth2-master\simple\src\main\resources\application.yml file and set the  clientId to the App ID and set the clientSecret to the App Secret.  These 2 pieces of information are on the Settings/Basic page when editing the app.
![oauth2config](https://user-images.githubusercontent.com/13824716/64748045-1a3bf800-d4ce-11e9-8a59-db80b274e970.PNG)

**Comment by IranCanul** [comment]
> I encountered the same issue as ocarlsen, which was resolved by creating my own app. Reading Facebooks documentation, localhost should work without SSL as long as the app is still in status 'In Development'.

it does not work

**Comment by dsyer** [comment]
The guide doesn’t use Facebook any more so this is obsolete.
